update release

diff --git a/.github/workflows/release-linux.yml b/.github/workflows/release-linux.yml
--- a/.github/workflows/release-linux.yml
+++ b/.github/workflows/release-linux.yml
@@ -10,42 +10,97 @@ permissions:
   contents: write
 
 jobs:
-  build-linux-release:
+  build:
+    permissions:
+        contents: write
+    name: Build and Release
     runs-on: ubuntu-latest
-
+    outputs:
+        BABOPLUGIN_VERSION: ${{ steps.BABOPLUGIN_VERSION.outputs.BABOPLUGIN_VERSION }}
     steps:
-      - name: Checkout
+      - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Setup .NET
+      - name: Set up .NET
         uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: "8.0.x"
+          dotnet-version: '8.0'
 
-      - name: Restore
-        run: dotnet restore
-
-      - name: Publish Release (linux-x64)
-        run: dotnet publish -c Release -r linux-x64 --self-contained false -o artifacts/publish
-
-      - name: Include cfg files
+      - name: Get BaboPlugin Version
+        id: BABOPLUGIN_VERSION
         run: |
-          mkdir -p artifacts/publish/cfg/BaboPlugin
-          cp -r cfg/BaboPlugin/. artifacts/publish/cfg/BaboPlugin/
-
-      - name: Create zip package
+            BABOPLUGIN_VERSION=$(grep -oP 'ModuleVersion\s*=>\s*"\K[^"]*' BaboPlugin.cs)
+            echo "BABOPLUGIN_VERSION=$BABOPLUGIN_VERSION" >> $GITHUB_ENV
+      - name: Build and Release Artifacts
         run: |
-          cd artifacts/publish
-          zip -r ../BaboPlugin-linux-x64.zip .
+          CSSHARP_VERSION=$(grep -Po '<PackageReference Include="CounterStrikeSharp.API" Version="\K\d+(\.\d+)*' BaboPlugin.csproj)
+          echo "Creating BaboPlugin base package with version: $BABOPLUGIN_VERSION"
+          dotnet publish -o package/addons/counterstrikesharp/plugins/BaboPlugin
+          cp -r cfg package 
+          cd package && zip -q -r ../BaboPlugin-$BABOPLUGIN_VERSION.zip * && cd ..
+    
+          echo "Creating package with CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION for Linux"
+          cd package/
+          echo "Installing CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION"
+          [ -e addons/counterstrikesharp ] && rm -rf addons/counterstrikesharp && echo "CounterStrikeSharp removed" || echo "old CounterStrikeSharp not found"
+          curl -s https://api.github.com/repos/roflmuffin/CounterStrikeSharp/releases/tags/v$CSSHARP_VERSION |
+              grep "/counterstrikesharp-with-runtime-linux-$CSSHARP_VERSION" |
+              cut -d : -f 2,3 |
+              tr -d \" |
+              head -n 1 |
+              wget -O cssharp-linux.zip -qi -
+          unzip -o cssharp-linux.zip -d .
+          rm cssharp-linux.zip
+          cd ../
 
-      - name: Upload build artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: BaboPlugin-linux-x64
-          path: artifacts/BaboPlugin-linux-x64.zip
+          dotnet publish -o package/addons/counterstrikesharp/plugins/BaboPlugin
 
-      - name: Upload to GitHub Release
-        if: startsWith(github.ref, 'refs/tags/')
+          cd package && zip -q -r ../BaboPlugin-$BABOPLUGIN_VERSION-with-cssharp-linux.zip * && cd ..
+
+          rm -r package/*
+
+          echo "Creating package with CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION for Windows"
+          cp -r cfg package
+          cd package/
+          echo "Installing CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION"
+          [ -e addons/counterstrikesharp ] && rm -rf addons/counterstrikesharp && echo "CounterStrikeSharp removed" || echo "old CounterStrikeSharp not found"
+          curl -s https://api.github.com/repos/roflmuffin/CounterStrikeSharp/releases/tags/v$CSSHARP_VERSION |
+              grep "/counterstrikesharp-with-runtime-windows-$CSSHARP_VERSION" |
+              cut -d : -f 2,3 |
+              tr -d \" |
+              head -n 1 |
+              wget -O cssharp-windows.zip -qi -
+          unzip -o cssharp-windows.zip -d .
+          rm cssharp-windows.zip
+          cd ../
+
+          dotnet publish -o package/addons/counterstrikesharp/plugins/BaboPlugin
+
+          cd package && zip -q -r ../BaboPlugin-$BABOPLUGIN_VERSION-with-cssharp-windows.zip * && cd ..
+
+      - name: Create Release
+        id: create_release
         uses: softprops/action-gh-release@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          files: artifacts/BaboPlugin-linux-x64.zip
+          name: BaboPlugin ${{ env.BABOPLUGIN_VERSION }}
+          tag_name: ${{ env.BABOPLUGIN_VERSION }}
+          body: |
+            Please see the [`CHANGELOG.md`](https://github.com/shobhit-pathak/BaboPlugin/blob/main/CHANGELOG.md) for details on changes.
+
+            Installation:
+            There are 3 files attached here:
+            One is the BaboPlugin-${{ env.BABOPLUGIN_VERSION }}.zip which only contains the BaboPlugin plugin files. Extract its contents in csgo/ directory of the server. (Prerequisite: Metamod and CounterStrikeSharp should be already installed on the server)
+            
+            Second one is BaboPlugin-${{ env.BABOPLUGIN_VERSION }}-with-cssharp-linux.zip which contains BaboPlugin plugin file as well as CounterStrikeSharp files (for linux) so that you don't have to install CounterStrikeSharp separately. Simply extract its contents in csgo/ directory of the server. 
+            Third one is BaboPlugin-${{ env.BABOPLUGIN_VERSION }}-with-cssharp-windows.zip which is same as above, but for Windows.
+            (Prerequisite: Metamod should be already installed on the server, rest CounterStrikeSharp and BaboPlugin will be installed once you extract the contents) (WITH CSSHARP RELEASE IS RECOMMENDED FOR FIRST TIME INSTALLERS)
+          draft: false
+          prerelease: false
+          files: |
+            BaboPlugin-${{ env.BABOPLUGIN_VERSION }}.zip
+            BaboPlugin-${{ env.BABOPLUGIN_VERSION }}-with-cssharp-linux.zip
+            BaboPlugin-${{ env.BABOPLUGIN_VERSION }}-with-cssharp-windows.zip
+
+      
